language: go

env:
  global:
    - GO111MODULE="on"
    - PATH="${PROTOC_TARGET}/bin:${PATH}"
    - PROTOC_RELEASE="https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip"
    - PROTOC_TARGET="${HOME}/protoc"

go:
  - 1.11.x
  - master

cache:
  - "${HOME}/protoc"

install:
  - if [ ! -d "${PROTOC_TARGET}" ]; then curl -fsSL "${PROTOC_RELEASE}" > "${PROTOC_TARGET}.zip"; fi
  - if [ -f "${PROTOC_TARGET}.zip" ]; then unzip "${PROTOC_TARGET}.zip" -d "${PROTOC_TARGET}"; fi
  - go get github.com/golang/protobuf/{proto,protoc-gen-go}
  - go get github.com/haya14busa/goverage

script:
  - make test-ci

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
